# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thirdFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Framework import Recommendation

class Ui_thirdFrame(object):
    def setupUi(self, thirdFrame):
        thirdFrame.setObjectName("thirdFrame")
        thirdFrame.resize(1054, 590)
        self.centralwidget = QtWidgets.QWidget(thirdFrame)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1111, 551))
        self.frame.setStyleSheet("background-color: rgb(72, 89, 53);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 40, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(230, 40, 361, 41))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame, clicked=lambda:self.SearchBook())
        self.pushButton.setGeometry(QtCore.QRect(650, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(147, 162, 103);")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(230, 100, 541, 401))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame, clicked=lambda:self.Back(thirdFrame))
        self.pushButton_2.setGeometry(QtCore.QRect(870, 490, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(147, 162, 103);")
        self.pushButton_2.setObjectName("pushButton_2")
        thirdFrame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(thirdFrame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1054, 26))
        self.menubar.setObjectName("menubar")
        thirdFrame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(thirdFrame)
        self.statusbar.setObjectName("statusbar")
        thirdFrame.setStatusBar(self.statusbar)

        self.retranslateUi(thirdFrame)
        QtCore.QMetaObject.connectSlotsByName(thirdFrame)

    def retranslateUi(self, thirdFrame):
        _translate = QtCore.QCoreApplication.translate
        thirdFrame.setWindowTitle(_translate("thirdFrame", "MainWindow"))
        self.label.setText(_translate("thirdFrame", "Enter User Id:"))
        self.pushButton.setText(_translate("thirdFrame", "Recommend"))
        self.pushButton_2.setText(_translate("thirdFrame", "Back"))

    def Back(self, thirdFrame):
        from main import Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        thirdFrame.close()
        self.window.show()

    def SearchBook(self):
        obj = Recommendation()
        user_inp = int(self.textEdit.toPlainText())
        print(f"Personalized recommendations for user: {user_inp}")
        recommendations = obj.personalized_book_recommendations1(user_inp)
        text = "\n".join(recommendations)
        self.textBrowser.setText(text)

        # for i in recommendation:
        #     print(f"- {i}")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    thirdFrame = QtWidgets.QMainWindow()
    ui = Ui_thirdFrame()
    ui.setupUi(thirdFrame)
    thirdFrame.show()
    sys.exit(app.exec_())
